### ISSUE TITLE
Unable to install it on Mac

### ISSUE THREAD

**Issue by mariusghitoiu** [geerlingguy/ansible-role-php#84]
Hi!

I am using ansible for the first time to create a VagrantBox for web development on CentOS 7. 

I was able to install geerlingguy.mysql and geerlingguy.repo-epel using the following commands on my Mac:
ansible-galaxy install geerlingguy.mysql -p ./provisioning/roles/
ansible-galaxy install geerlingguy.repo-epel -p ./provisioning/roles/
and they were successful installed. Thank you for creating these!

When I try to install geerlingguy.php I get the following error: 

```
 downloading role 'php', owned by geerlingguy
ERROR! Unexpected Exception: object of type 'NoneType' has no len()
to see the full traceback, use -vvv
```

**When I run the same command with -vvv I get: **
```

No config file found; using defaults
Opened /Users/marius/.ansible_galaxy
Validate TLS certificates: True
Connecting to galaxy_server: https://galaxy.ansible.com
Base API: https://galaxy.ansible.com/api/v1
Installing role geerlingguy.php 
Opened /Users/marius/.ansible_galaxy
Validate TLS certificates: True
Connecting to galaxy_server: https://galaxy.ansible.com
Base API: https://galaxy.ansible.com/api/v1
- downloading role 'php', owned by geerlingguy
https://galaxy.ansible.com/api/v1/roles/?owner__username=geerlingguy&name=php
https://galaxy.ansible.com/api/v1/roles/432/versions/?page_size=50
https://galaxy.ansible.com/api/v1https://galaxy.ansible.com/api/v1/roles/432/versions/?page=2&page_size=50
ERROR! Unexpected Exception: object of type 'NoneType' has no len()
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-galaxy", line 86, in <module>
    sys.exit(cli.run())
  File "/usr/local/lib/python2.7/site-packages/ansible/cli/galaxy.py", line 153, in run
    self.execute()
  File "/usr/local/lib/python2.7/site-packages/ansible/cli/__init__.py", line 114, in execute
    fn()
  File "/usr/local/lib/python2.7/site-packages/ansible/cli/galaxy.py", line 404, in execute_install
    installed = role.install()
  File "/usr/local/lib/python2.7/site-packages/ansible/galaxy/role.py", line 210, in install
    if len(role_versions) > 0:
TypeError: object of type 'NoneType' has no len()


```

From what I can tell this url is incorect 
**https://galaxy.ansible.com/api/v1https://galaxy.ansible.com/api/v1/roles/432/versions/?page=2&page_size=50**

Any idea what am I missing? 

Thank you!

**Comment by oxyc** [comment]
This is an upstream issue with the release of Galaxy v2.0.1 yesterday https://github.com/ansible/galaxy-issues/issues/134

**Comment by mariusghitoiu** [comment]
Got it! Thanks for the update.

**Comment by oxyc** [comment]
@mariusghitoiu upstream they mentioned it should be fixed this evening :+1:

**Comment by geerlingguy** [comment]
What @oxyc said; I'm going to close this issue, but feel free to open a new one to track things if it doesn't work later tonight or tomorrow morning.

**Comment by freshtonic** [comment]
This is still a problem as of 27th May.

**Comment by geerlingguy** [comment]
@freshtonic - I've installed Drupal VM (and other projects using this role) fresh on a couple new computers (that never had Ansible installed) in the past day, and didn't encounter the problem.

Can you see what version of Ansible you have installed? And also try again after a little time to see if the error keeps happening?

**Comment by freshtonic** [comment]
@geerlingguy it was 1.9.4. Upgrading to 1.9.6 solved the issue.

**Comment by geerlingguy** [comment]
Ah yes, there was an issue pre-1.9.6 with version numbering and galaxy. Glad it worked!

**Comment by llwp** [comment]
@geerlingguy would you consider an ansible version test?  I was running an older version of ansible due to Mac OS & brew update/upgrade needed.  Pretty simple fix, but the fail on messages as evidenced in this thread are less than intuitive.

**Comment by kentr** [comment]
This is happening for me with  Ansible `2.4.0.0`.  

Other roles that precede this in the DrupalVM `requirements.yml` work OK.

```
Processing role geerlingguy.php 
Opened /Users/Work/.ansible_galaxy
Initial connection to galaxy_server: https://galaxy.ansible.com
Base API: https://galaxy.ansible.com/api/v1
- downloading role 'php', owned by geerlingguy
https://galaxy.ansible.com/api/v1/roles/?owner__username=geerlingguy&name=php
ERROR! Unexpected Exception, this is probably a bug: Failed to connect to galaxy.ansible.com at port 443: [Errno 8] nodename nor servname provided, or not known
the full traceback was:

Traceback (most recent call last):
  File "/opt/local/bin/ansible-galaxy", line 106, in <module>
    exit_code = cli.run()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible/cli/galaxy.py", line 150, in run
    self.execute()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible/cli/__init__.py", line 154, in execute
    fn()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible/cli/galaxy.py", line 392, in execute_install
    installed = role.install()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible/galaxy/role.py", line 219, in install
    role_data = api.lookup_role_by_name(self.src)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible/galaxy/api.py", line 56, in wrapped
    return method(self, *args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible/galaxy/api.py", line 193, in lookup_role_by_name
    data = self.__call_galaxy(url)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible/galaxy/api.py", line 56, in wrapped
    return method(self, *args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible/galaxy/api.py", line 93, in __call_galaxy
    timeout=20)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible/module_utils/urls.py", line 951, in open_url
    r = urllib_request.urlopen(*urlopen_args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 427, in open
    req = meth(req)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible/module_utils/urls.py", line 765, in http_request
    raise ConnectionError('Failed to connect to %s at port %s: %s' % (self.hostname, self.port, to_native(e)))
ConnectionError: Failed to connect to galaxy.ansible.com at port 443: [Errno 8] nodename nor servname provided, or not known
```
